# Generated by Django 5.1.4 on 2024-12-15 21:16

import datetime
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager_app', '0001_pgvector_extention_enabling'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextEmbedding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Vector embeddings of the file content', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField()),
                ('source', models.CharField(choices=[('Telegram', 'telegram'), ('Mattermost', 'mattermost')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('timeout', models.DurationField(verbose_name='Timeout')),
            ],
        ),
        migrations.CreateModel(
            name='ModelSettingsForSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Prompt')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryGenerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.DurationField(verbose_name='Frequency')),
                ('timestamp', models.TimeField(verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='ChatContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
                ('embeddings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.contextembedding')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('surname', models.CharField(max_length=200, verbose_name='Surname')),
                ('registration_time', models.DateTimeField()),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.credentials')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('context', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager_app.chatcontext')),
                ('employees', models.ManyToManyField(to='manager_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('notification_date', models.DateTimeField()),
                ('text', models.TextField(verbose_name='text')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.chat')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.employee')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.hashtag')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
                ('text', models.TextField(verbose_name='text')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='time')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.chat')),
                ('model_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.modelsettingsforsummary')),
                ('generation_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.summarygenerationsettings')),
            ],
        ),
    ]
