# Generated by Django 5.1.4 on 2024-12-20 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelsettingsforsummary',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='generation_settings',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='model_settings',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_source',
            field=models.CharField(choices=[('Telegram', 'telegram'), ('Mattermost', 'mattermost')], default='Telegram', max_length=20),
        ),
        migrations.AddField(
            model_name='chat',
            name='generation_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_app.summarygenerationsettings'),
        ),
        migrations.AddField(
            model_name='chat',
            name='model_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_app.modelsettingsforsummary'),
        ),
        migrations.AddField(
            model_name='chat',
            name='source_chad_id',
            field=models.CharField(max_length=200, null=True, verbose_name='Source Chat ID'),
        ),
        migrations.AddField(
            model_name='modelsettingsforsummary',
            name='system_prompt',
            field=models.TextField(default='Ты — Сайга, русскоязычный автоматический ассистент. Ты разговариваешь с людьми и помогаешь им.', verbose_name='System Prompt'),
        ),
        migrations.AddField(
            model_name='modelsettingsforsummary',
            name='user_prompt',
            field=models.TextField(default='Сделай краткое тезисное резюме по результатам обсуждений в чате. Содержание чата ниже.', verbose_name='User Prompt'),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='source',
            field=models.CharField(choices=[('Telegram', 'telegram'), ('Mattermost', 'mattermost')], default='Telegram', max_length=20),
        ),
    ]
