# Generated by Django 5.1.4 on 2025-01-10 11:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_remove_modelsettingsforsummary_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelResponseStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=200, verbose_name='Name')),
                ('system_prompt', models.TextField(default='Ты — Сайга, русскоязычный автоматический ассистент. Ты разговариваешь с людьми и помогаешь им.', verbose_name='System Prompt')),
                ('user_prompt', models.TextField(default='Сделай краткое тезисное резюме по результатам обсуждений в чате. Содержание чата ниже.', verbose_name='User Prompt')),
            ],
        ),
        migrations.RenameModel(
            old_name='SummaryGenerationSettings',
            new_name='GenerationSettings',
        ),
        migrations.RemoveField(
            model_name='chatcontext',
            name='embeddings',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='context',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='model_settings',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='chat',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.chat')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ModelResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='time')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.chat')),
                ('response_strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_app.modelresponsestrategy')),
            ],
        ),
        migrations.DeleteModel(
            name='ContextEmbedding',
        ),
        migrations.DeleteModel(
            name='ChatContext',
        ),
        migrations.DeleteModel(
            name='ModelSettingsForSummary',
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
