# Generated by Django 5.1.4 on 2025-01-15 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_modelresponsestrategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='credentials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_app.credentials'),
        ),
    ]
