# Generated by Django 5.1.4 on 2025-01-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0005_alter_employee_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='note',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='note',
            name='employee',
        ),
        migrations.DeleteModel(
            name='HashTag',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
