# Generated by Django 5.1.4 on 2025-01-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0006_remove_note_hashtag_remove_note_chat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='source_chad_id',
            new_name='source_chat_id',
        ),
    ]
