# Generated by Django 5.1.4 on 2025-01-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0007_rename_source_chad_id_chat_source_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='surname',
        ),
    ]
