# Generated by Django 5.1.4 on 2025-01-20 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0008_remove_employee_name_remove_employee_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField()),
                ('source', models.CharField(choices=[('Telegram', 'telegram'), ('Mattermost', 'mattermost')], default='Telegram', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='credentials',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='registration_time',
        ),
        migrations.RemoveField(
            model_name='message',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=200, null=True, verbose_name='Surname'),
        ),
        migrations.AddField(
            model_name='employee',
            name='accounts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_app.employeeaccount'),
        ),
        migrations.AddField(
            model_name='message',
            name='employee_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_app.employeeaccount'),
        ),
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
